import React, { useState, useEffect } from "react";
import Head from "next/head";
import Table from "@/components/table/table";
import styles from "@/styles/Home.module.css";

export default function UserTable() {
  const [userData, setUserData] = useState([]);
  const [fieldsToShow, setFieldsToShow] = useState([]);

  const handleApiChange = (e) => {
    const { value } = e.target;
    setFieldsToShow([]);
    switch (value) {
      case "bmw_mercedes_income_less_5":
        fetchData("/api/users/bmw_mercedes_income_less_5", [
          "fname",
          "lname",
          "email",
          "gender",
          "phone",
          "car",
          "income",
          "city",
        ]);
        break;
      case "male_phone_price_gt_10000":
        fetchData("/api/users/male_phone_price_gt_10000", [
          "fname",
          "lname",
          "email",
          "gender",
          "phone",
          "income",
          "quote",
          "city",
        ]);
        break;
      case "bmw_mercedes_audi_email_no_digit":
        fetchData("/api/users/bmw_mercedes_audi_email_no_digit", [
          "fname",
          "lname",
          "email",
          "car",
          "city",
        ]);
        break;
      default:
        break;
    }
  };

  async function fetchData(apiPath, fieldsToShow) {
    try {
      const res = await fetch(apiPath);
      const data = await res.json();
      setUserData(
        data.map((user) =>
          fieldsToShow.reduce((filteredUser, field) => {
            filteredUser[field] = user[field];
            return filteredUser;
          }, {})
        )
      );
      setFieldsToShow(fieldsToShow);
    } catch (error) {
      console.error(error);
    }
  }

  useEffect(() => {
    // Fetch user data from the server
    async function fetchData() {
      const res = await fetch("/api/users/bmw_mercedes_income_less_5");
      const data = await res.json();
      setUserData(data);
    }
    fetchData();
  }, [userData]);

  console.log({ userData });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>User Data</h1>
      <select onChange={handleApiChange}>
        <option value="">--Select an API--</option>
        <option value="bmw_mercedes_income_less_5">
          BMW/Mercedes with income less than $5
        </option>
        <option value="male_phone_price_gt_10000">
          Male users with phone price greater than $10,000
        </option>
        <option value="bmw_mercedes_audi_email_no_digit">
          BMW/Mercedes/Audi with email that doesnot contain digits
        </option>
      </select>
      {!!fieldsToShow.length && (
        <Table userData={userData} fieldsToShow={fieldsToShow} />
      )}
    </div>
  );
}
