import React, { useState } from "react";
import Head from "next/head";
import Table from "@/components/table/table";
import styles from "@/styles/Home.module.css";
import { queries } from "@/pages/api/query";

const fetchData = async (url) => {
  const BASE_URL = "api/query/";
  const response = await fetch(`${BASE_URL}/${url}`);

  return await response.json();
};

// we can use this code to send the users data to Home component by rendering on server

// export const getServerSideProps = async () => {
//   try {
//     await connectMongo(); // connect to mongoDB

//     const users = await User.find();

//     console.log("data fetched");

//     return {
//       props: {
//         users: JSON.parse(JSON.stringify(users)),
//       },
//     };
//   } catch (error) {
//     console.log(error);
//     return {
//       notFound: true,
//     };
//   }
// };

export default function Home() {
  const [selectedQuery, setSelectedQuery] = useState("");
  const [userResults, setUserResults] = useState([]);

  const handleApiChange = async (e) => {
    try {
      setSelectedQuery(e.target.value);

      e.preventDefault();
      const results = await queries[selectedQuery]();
      setUserResults(results.data);
      console.log(userResults);
    } catch (error) {
      console.log("error in handling api change " + error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.heading}>User Data</h1>
      <select onChange={handleApiChange} className={styles.menu}>
        <option value="">--Select an API--</option>
        <option value="1">BMW/Mercedes with income less than $5</option>
        <option value="2">
          Male users with phone price greater than $10,000
        </option>
        <option value="3">
          BMW/Mercedes/Audi with email that does not contain digits
        </option>
      </select>
      {!!userResults.length && <Table userData={userResults} />}
    </div>
  );
}
